backend:
  name: github
  repo: benjaminmodayil/modayilme

media_folder: static/assets
public_folder: /assets

publish_mode: editorial_workflow

collections:
  - name: blog
    label: Posts
    folder: src/pages/posts/blog
    create: true
    fields:
      - { name: layout, label: Layout, default: "blog"}
      - { name: type, label: Type, default: "blog"}
      - { name: title, label: Title}
      - { name: tldr, label: TL;DR}
      - { name: date, label: Created At, widget: date }
      - { name: path, label: path, widget: string, default: "/blog" }
      - { name: body, label: Post, widget: markdown}
  - name: work
    label: Work
    folder: src/pages/posts/work
    create: true
    fields:
      - { name: layout, label: Layout, default: "work"}
      - { name: type, label: Type, default: "work"}
      - { name: title, label: Title}
      - { name: tldr, label: TL;DR}
      - { name: imageNote, label: Image Note}
      - { name: svgName, label: SVG File Name}
      - { name: description, label: Description}
      - { name: website, label: Website}
      - { name: headerColor, label: Header BG Color}
      - { name: metaBackground, label: Meta BG Color}
      - { name: linkColor, label: Link Color}
      - { name: textColor, label: Text Color}
      - { name: textBackground, label: Post BG Color}
      - { name: website, label: Website}
      - { name: date, label: Created At, widget: date }
      - { name: path, label: path, widget: string, default: "/work" }
      - { name: body, label: Post, widget: markdown}